version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5000"
    networks:
      - internal-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80" 
    depends_on:
      - webapp
    networks:
      - internal-network

networks:
  internal-network:
    driver: bridge

